services:
  - type: web
    name: technomir-app
    env: go
    plan: free
    region: frankfurt
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TECHNOMIR_TOKEN
        sync: false
